config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end
  get "sessions/create" 
  get "sessions/destroy"

  # Special route for cart functions 
  get "/cart", to: "cart_items#show", as: "cart"
  post "/add_item", to: "cart_items#add_item", as: "add_item"
  post "/remove_item", to: "cart_items#remove_item", as: "remove_item"
  post "/clear", to: "cart_items#clear", as: "clear"
  post "/place_order", to: "cart_items#place_order", as: "place_order"
  post "/orders/new", to: 'orders#new', as: "place_new_order"

  # Shipping list
  get "/shipping", to: "orders#shipping", as: "shipping"
  post "/add_shipping", to: "orders#add_shipping", as: "add_shipping"
  post "/remove_shipping", to: "orders#remove_shipping", as: "remove_shipping"
  post "/ship_items", to: "orders#ship_items", as: "ship_items"

  # Baking List
  get "/baking", to: "orders#baking", as: "baking"

  # Item toggle
  post "/toggle", to: "items#toggle", as: "toggle"

  # Admin Dash
  get "/sales_dash", to: "home#sales_dash", as: "sales_dash"
  post "/sales_dash", to: "home#sales_dash", as: "post_sales_dash"
  get "/customer_dash", to: "home#customer_dash", as: "customer_dash"
  get "/item_dash", to: "home#item_dash", as: "item_dash"

  # get 'customers/new', to: 'customers#new', as: :signup
  # get 'users/new', to: 'users#new', as: :signup
  # get 'user/edit', to: 'users#edit', as: :edit_current_user
  
  # get 'sessions', to: 'sessions#new', as: :login
  get 'sessions', to: 'sessions#destroy', as: 'logout_user'
  
  # Set the root url
  root :to => 'home#home'
  
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<!-- Footer --> 
<div class="row footer">

<div class="col align-self-left text-left pl-4">
  <span>Webmaster: <a href="mailto:mkornyev@gmail.com">Max Kornyev&nbsp;&copy; 2019</a>&nbsp;|&nbsp;</span>
  <span><a><%= link_to 'Home', home_path %></a></span>
  <div class="social">
	  <span><a><%= link_to 'About', about_path %></a></span>&nbsp;|
	  <span><a><%= link_to 'Contact Us', contact_path %></a></span>&nbsp;|
	  <span><a><%= link_to 'Privacy Policy', privacy_path %></a></span>
  </div>
</div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col" style="margin: 5%;">
    <fieldset class="border mx-4 pl-3 mb-3">
      <legend  class="w-auto"><%= type_of_form %></legend><br>

      <% if controller_name == "addresses" && action_name == "edit" %>
        
        <%= simple_form_for(object) do |f| %>

        <!-- Display Error -->
        <% if object.errors.any? %>
        
          <% object.errors.full_messages.each do |message| %>
            <% if message == "User must exist" %>
            <% else %> 
            <div class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
              <%= message %>
            </div>
            <% end %> 
          <% end %>

        <% end %>  

        <div class="form-group" style="margin-right: 5%;">
            <%= render partial: "#{fields}", locals: { f: f } %>
        </div>

        <%= f.button :submit, class: "btn btn-primary", style: "margin-bottom: 1%;"%>
        <%= link_to 'Back', :back, class: "btn btn-outline-primary", style: "margin-bottom: 1%;" %>

        <% end %>

      <% else %>

        <%= form_for(object) do |f| %>
        
        <!-- Display Error -->
        <% if object.errors.any? %>
        
          <% object.errors.full_messages.each do |message| %>
            <% if message == "User must exist" %>
            <% else %> 
            <div class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
              <%= message %>
            </div>
            <% end %> 
          <% end %>

        <% end %>  

        <div class="form-group" style="margin-right: 5%;">
            <%= render partial: "#{fields}", locals: { f: f } %>
        </div>

        <%= f.button :Submit, class: "btn btn-primary", style: "margin-bottom: 1%;"%>
        <%= link_to 'Back', :back, class: "btn btn-outline-primary", style: "margin-bottom: 1%;" %>

        <% end %>

      <% end %> 


    </fieldset>
  </div>
</div>

app/views/partials/_item_list.html.erb
<% if @all_items.nil? || @all_items.empty? %>
    <div class='col-9'>
      Nothing currently available. Try, try again!
    </div>
<% else %>
      <div class='row' style="padding-top: 1%; margin: auto;">
      <%= will_paginate @all_items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
      
      <div class="row" style=" width: 92%; margin-left: 8.4%;">
      <% @all_items.each do |item| %>

      <!-- Modal (w/show trigger) -->
      <div class="card" style="width: 18rem; margin: 3%;">

        <% if !item.picture.nil? %>
          <%= image_tag item.picture, class: 'card-img-top', style: "height: 54%; width: 100%;"%>
        <% else %>
        <% if item.category == 'bread' %>
            <%= image_tag("bread.jpg", class: 'card-img-top', style: "")%>
          <% elsif item.category == 'muffins' %>
            <%= image_tag("muffins.jpg", class: 'card-img-top', style: "" )%>
          <% elsif item.category == 'pastries' %>
            <%= image_tag("pastries.jpg", class: 'card-img-top', style: "")%>
          <% end %>
      <% end %>
          
        <div class="card-body">
          <h5 class="card-title"><%= item.name %></h5>
          <p class="card-text">
          <%= number_to_currency item.current_price %> | <%= item.units_per_item %> <%= item.category == 'bread' ? 'loaf' : item.category %><br>
          <%= truncate item.description, length: 57 %> 
          </p>
          <%= link_to "See more", item_path(item), {:style=>'text-decoration: none;', :class => 'btn btn-outline-primary btn-md center-block' } %>
          <% if logged_in? && (current_user.role?(:admin) || current_user.role?(:customer)) %>
            <%= button_to 'Add to Cart', {:controller => "cart_items", :action => "add_item", :item_id => item.id}, :method=>:post, params: {item_id: item.id}, class: "btn btn-primary", style: "margin-top: 5px;"  %>
          <% else %>
          <% end %> 
        </div>
      </div>

      <% end %>
      </div>

      <div class='row' style="margin: auto;">
      <%= will_paginate @all_items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
      </div>
      
<% end %>

<!-- 
<%# unless @all_items.nil? || @all_items.empty? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="300">Name</th>
        <th width="100">Price</th>
        <th width="100">Units</th>
        <%# if controller.controller_name == 'orders' %>
          <th width="100">&nbsp;</th>
        <%# end %>
      </tr>
    </thead>
    <tbody>
      <%# @all_items.each do |item| %>
        <tr>
          <td><%# link_to item.name, item_path(item) %></td>
          <td><%# number_to_currency item.current_price %></td>
          <td><%# item.units_per_item %> <%# item.category == 'bread' ? 'loaf' : item.category %></td>
          
          
          <%# if controller.controller_name == 'orders' %>
            <td>
              <%# link_to(add_to_cart_path(item.id), class: 'button tiny radius') do %>
                &nbsp;Add to Cart&nbsp;
              <%# end %>
            </td>
          <%# end %>
          

        </tr>
      <%# end %>
    </tbody>
  </table><br>
  <%# will_paginate @all_items, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>
<%# end %>
-->

app/views/partials/_item_list_admin.html.erb
<% if @all_items.nil? || @all_items.empty? %>
  <p style="padding-top: 20px;">No items in the system!</p>
<% else %>
  <div style="padding-top: 2%;">
  <%= will_paginate @all_items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  </div>
  <div style="display: inline; margin-left: .5%; margin-bottom: 5px; padding-top: 2%;">
    <%= link_to "Add a New Item", new_item_path, class: 'btn btn-primary' %> 
  </div>
  
  <table class="table table-striped" style="width: 100%; border: 1px;">
    <thead>
      <tr>
        <th width="50">Name</th>
        <th width="50">Price</th>
        <th width="50">Units</th>        
        <th width="50">Active</th> 
        <th width="50">Active Toggle</th> 
        <th width="50">Edit</th>       
        <th width="50">Delete</th>     
        <th width="50">Add to Cart</th>        
      </tr>
    </thead>
    <tbody>
      <% @all_items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item_path(item) %></td>
          <td><%= number_to_currency item.current_price %></td>
          <td><%= item.units_per_item %> <%= item.category == 'bread' ? 'loaf' : item.category %></td>
          <td>&nbsp;&nbsp;
            <% if item.active %>
              <i class="material-icons">done</i>
            <% else %>
            <% end %>
          </td>
          <td>
            <%= button_to 'Toggle', {:controller => "items", :action => "toggle", :item_id => item.id}, :method=>:post, params: {item_id: item.id}, class: 'btn btn-primary', style: 'margin-left: 10%;' %>
          </td>
          <td>
            <%= link_to edit_item_path(item) do %>
              <i class="material-icons">edit</i>
            <% end %>
          </td>
          <td>&nbsp;&nbsp;
            <%= link_to(item_path(item), method: :delete, data: { confirm: 'Are you sure?' }) do %>
              <i class="material-icons">delete</i>
            <% end %>
          </td>
          
          <td>
            <% if item.active %> 
            <%= button_to '+', {:controller => "cart_items", :action => "add_item", :item_id => item.id}, :method=>:post, params: {item_id: item.id}, class: 'btn btn-primary', style: 'margin-left: 20%;' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  <%= will_paginate @all_items, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
  
<% end %>

app/views/partials/_nav_baker.html.erb
<!-- NavBar --> 
<div class="row navbar">
<div class="col align-self-left text-left pl-4">
  <!-- Logo -->
  <%= link_to image_tag("logo.png"), :controller => 'home', :action => 'home' %>

  <!-- Links -->
    <%= link_to 'Items', items_path, class: 'nav-link underline_effect' %>
    <%= link_to 'Baking List', baking_path, class: "nav-link underline_effect" %>

    <!-- Logout -->
    <div style="padding-left: 6px;">
      <li style="font-size: .8em;" class="underline_effect"><%= link_to "Log Out", logout_user_path %></li>
    </div>
</div>
</div>

app/views/partials/_nav_customer.html.erb
<!-- NavBar --> 
<div class="row navbar">
<div class="col align-self-left text-left pl-4">
  <!-- Logo -->
  <%= link_to image_tag("logo.png"), :controller => 'home', :action => 'home' %>

  <!-- Links -->
    <%= link_to 'Baked Goods', items_path, class: 'nav-link underline_effect' %>
    <%= link_to "My Account", customer_path(current_user.customer), class: "nav-link underline_effect" %>

    <!-- Logout -->
    <div style="padding-left: 6px;">
      <li style="font-size: .8em;" class="underline_effect"><%= link_to "Log Out", logout_user_path %></li>
    </div>
    <!-- Cart -->
    <span style="float: right; margin-right: 25px; margin-top: 15px;">
      <% if !session[:cart].empty? %>
        <div class="number_overlay" style="border-color: red; width: 24px; height: 30px; border-radius: 15px; position: absolute; top: 10px; right: 160px; z-index: 10; background-color: red;">
          <% if (session[:cart].values.sum) < 10 %>
            <p style="color: white; padding-left: 7px;">
              <%= (session[:cart].values.sum) %>
            </p>
          <% else %>
            <p style="color: white; padding-left: 2px;">
              <%= (session[:cart].values.sum) %>
            </p>
          <% end %>
        </div>
      <% else %>
      <% end %>
      <%= link_to image_tag("cart.png", :size => "48x48"), cart_path, class: 'underline_effect', style: 'padding-bottom: 11px' %> 
    </span>
</div>
</div>

app/views/partials/_nav_guest.html.erb
<!-- NavBar --> 
<div class="row navbar">
<div class="col align-self-left text-left pl-4">
  <!-- Logo -->
  <%= link_to image_tag("logo.png"), :controller => 'home', :action => 'home' %>

  <!-- Links -->
    <%= link_to 'Baked Goods', items_path, class: 'nav-link underline_effect' %>
    
    <div class="cart" style="text-align: center;">
      <li class="underline_effect" style="font-size: .8em; text-align: center;">
        <%= link_to 'Sign Up', new_customer_path %>
      </li>
    </div>

    <!-- Login -->
    <div class="login" style="text-align: center; text-align: center;">
      <li class="underline_effect" style="font-size: .8em;"><%= link_to 'Log In', login_path %>
      </li>
    </div>
</div>
</div>

app/views/partials/_nav_shipper.html.erb
<!-- NavBar --> 
<div class="row navbar">
<div class="col align-self-left text-left pl-4">
  <!-- Logo -->
  <%= link_to image_tag("logo.png"), :controller => 'home', :action => 'home' %>

    <!-- Links -->
    <%= link_to 'Items', items_path, class: 'nav-link underline_effect' %>
    <%= link_to 'Shipping List', shipping_path, class: 'nav-link underline_effect' %>
    

    <!-- Logout -->
    <div style="padding-left: 6px;">
      <li style="font-size: .8em;" class="underline_effect"><%= link_to "Log Out", logout_user_path %></li>
    </div>
</div>
</div>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  
  <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
      &nbsp;<%= "Edit #{opt}" %>
  <% end %>
  &nbsp;&nbsp;
  
  <% if controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>

</div>

app/views/partials/_order_item_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th width="100">Quantity</th>
      <th width="300">Item</th>
      <th width="100">Unit Price</th>
      <th width="100">Subtotal</th>
      <% if controller.controller_name == 'home' %>
        <th>&nbsp;</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% order_items.each do |oi| %>
      <tr>
        <td align="center"><%= oi.quantity %></td>
        <td><%= link_to oi.item.name, item_path(oi.item) %></td>
        <td align="center"><%= number_to_currency oi.item.price_on_date(date) %></td>
        <td align="right"><%= number_to_currency oi.subtotal(date) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <% if controller.controller_name == 'home' %>
          <td>
            <% if oi.shipped_on.nil? %>
              <%= link_to(image_tag('check_black.gif'), mark_shipped_path(oi.id), method: 'patch') %>
            <% else %>
              <%= link_to(image_tag('check_green.gif'), mark_unshipped_path(oi.id), method: 'patch') %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/partials/_previous_orders.html.erb
<% unless previous_orders.empty? %>
  <div class="panel clearfix">
    <h3>Order History</h3>
    <table>
      <thead>
        <tr>
          <th width="120">Date</th>
          <th width="100">Amount</th>
        </tr>
      </thead>
      <tbody>
      <% previous_orders.each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </table>
  </div>
<% end %>

app/views/partials/_topbar.html.erb
<div class="row valign-wrapper" id="topbar">
  <div class="col s1">
    <%# link_to(image_tag('logos/logo_v2_80x80.png'), home_path) %>
  </div>
  <div class="col s10">
    <h2><%= link_to "Baking Factory", home_path, class: "home_link" %></h2>
  </div>
  <div class="col s1">
    &nbsp;
  </div>
</div>