config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end
  get "sessions/create" 
  get "sessions/destroy"

  # Special route for cart functions 
  get "/cart", to: "cart_items#show", as: "cart"
  post "/add_item", to: "cart_items#add_item", as: "add_item"
  post "/remove_item", to: "cart_items#remove_item", as: "remove_item"
  post "/clear", to: "cart_items#clear", as: "clear"
  post "/place_order", to: "cart_items#place_order", as: "place_order"
  post "/orders/new", to: 'orders#new', as: "place_new_order"

  # Shipping list
  get "/shipping", to: "orders#shipping", as: "shipping"
  post "/add_shipping", to: "orders#add_shipping", as: "add_shipping"
  post "/remove_shipping", to: "orders#remove_shipping", as: "remove_shipping"
  post "/ship_items", to: "orders#ship_items", as: "ship_items"

  # Baking List
  get "/baking", to: "orders#baking", as: "baking"

  # Item toggle
  post "/toggle", to: "items#toggle", as: "toggle"

  # Admin Dash
  get "/sales_dash", to: "home#sales_dash", as: "sales_dash"
  post "/sales_dash", to: "home#sales_dash", as: "post_sales_dash"
  get "/customer_dash", to: "home#customer_dash", as: "customer_dash"
  get "/item_dash", to: "home#item_dash", as: "item_dash"

  # get 'customers/new', to: 'customers#new', as: :signup
  # get 'users/new', to: 'users#new', as: :signup
  # get 'user/edit', to: 'users#edit', as: :edit_current_user
  
  # get 'sessions', to: 'sessions#new', as: :login
  get 'sessions', to: 'sessions#destroy', as: 'logout_user'
  
  # Set the root url
  root :to => 'home#home'
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

  def about
  end

  def privacy
  end

  def contact
  end

  def sales_dash
  	# Total goods 
  	order_item_hash = Hash.new
  	OrderItem.all.each do |oi|
  		if order_item_hash[oi.item_id].nil?
  			order_item_hash[oi.item_id] = oi.quantity
  		else
  			order_item_hash[oi.item_id] = order_item_hash[oi.item_id] + oi.quantity
  		end
  	end 
  	@goods_count = order_item_hash.values.sum 

  	# Total sales 
  	@total_sales = Order.all.map{|o| o.grand_total}.sum

  	# Earliest order (weeks ago)
  	@weeks = TimeDifference.between(Order.order(:date).first.date, Time.now).in_weeks.floor

  	# Looks back X weeks to find orders
  	if params[:weeks].present? 
  		@orders = sales_chart_data(params[:weeks].to_i)  		
  	else
		@orders = sales_chart_data(@weeks)  		
  	end
  	
  end

  def sales_chart_data(week_count)
  	# Sales for each day 
  	(week_count.weeks.ago.to_date..Date.today).map do |date|
  		{
  		date: date.strftime('%F'), 
  		sales: Order.where(date: date).sum(:grand_total)
  		}
  	end
  end

  def customer_dash
  	# Total Customers
  	@customer_count = Customer.all.count 
  	@active_customer_count = Customer.all.active.count 
  	@avg_address_count = ((Address.all.count) / (@customer_count))
  	@avg_address_count = @avg_address_count.floor
  	@customers = customer_chart_data
  	@customers = @customers.sort_by{ |arr| arr[:value] }
  end

  def customer_chart_data
  	# Customer order counts
  	(Customer.all).map do |c|
  		{
  		label: c.name,
  		value: Order.where(customer_id: c.id).size
  		}
  	end
  end

  def item_dash
  	# Total Items
  	@item_count = Item.all.count 
  	@active_item_count = Item.all.active.count 
  	@items = item_chart_data
  	@items = @items.sort_by{ |arr| arr[:value] }
  end

  def item_chart_data
  	# Customer order counts
  	(Item.all).map do |i|
  		{
  		label: i.name,
  		value: OrderItem.where(item_id: i.id).map{|oi| oi.quantity}.sum
  		}
  	end
  end

end

app/views/home/about.html.erb
<div class="row">
  <div class="col" style="margin: 5%;">
    <fieldset class="border mx-4 pl-3 mb-3">
        <legend  class="w-auto">About A &amp; M Bread Express</legend><br>
        <p>
        	The A & M Baking factory is a sample ecommerce business owned by Alex & Mark Heimann, with their Web Application designed by Max Kornyev.<br>
            Their only business goal is to provide the freshest bread to their loyal customers.<br><br>
            Why are you still here? Check out the <a href="items">bread.</a>
        </p>
  </div>
</div>

app/views/home/contact.html.erb
<div class="row">
	<div class="col" style="margin: 5%;">


		<fieldset class="border mx-4 pl-3 mb-3">
   			<legend  class="w-auto">Contact the Baking Factory</legend><br>
			<table cellpadding="3">
				<tr>
					<td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
					<td>Maksym Kornyev</td>
				</tr>
				<tr>
					<td>Email:</td>
					<td>
					<%= mail_to("mkornyev@gmail.com", "mkornyev@gmail.com", :encode => "javascript") %> 
					</td>
				</tr>
				<tr>
					<td>Phone:</td>
					<td>315-296-5003</td>
				</tr>
			</table>	
		</fieldset>

		<p class="note"><br>*This WebApp is built using the Rails framework, for 67-272, Application Design and Development.  
			
			<p>&nbsp;</p>
			<p>&nbsp;</p>
	</div>
</div>

app/views/home/customer_dash.html.erb
<% if logged_in? && current_user.role?(:admin) %>
	
	<div class="row">
		<div class="col" style="margin: 5%; margin-top: 1%;">
			
			<h1><span style="color: #ffc107">Baking Factory</span> Command Center:</h1><br><br>

			<ul class="nav nav-tabs">
			  <li class="nav-item">
			    <%= link_to 'Sales Insights', sales_dash_path, class: "nav-link" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Customer Insights', customer_dash_path, class: "nav-link active" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Item Insights', item_dash_path, class: "nav-link" %>
			  </li>
			</ul>

			<div style="border: 1px solid #e5e4e2; border-top: none; display: inline;">
				<p style="width: 40%; margin: 5%; margin-top: 0px;">
				Total Customers in System: <strong><%= @customer_count %></strong><br>
				Total Active Customers: <strong><%= @active_customer_count %></strong><br>
				Avg # of Addresses per Customer: <strong><%= @avg_address_count %></strong><br><br>
				<span style="color: #a3a3a3;">To view each customer's order share, refer to the chart below.</span>
				</p>

				<hr>
				<h5 style="margin-left: 45%; text-decoration: underline;">Customer Order Share:</h5>
				<%= content_tag :div, "", id: "morris_chart", data: {customers: @customers } %>

			</div>


		</div>
	</div>

	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

	<script type="text/javascript">
		new Morris.Bar({
		  element: 'morris_chart',
		  data: $('#morris_chart').data('customers'),
		  xkey: 'label',
		  // A list of names of data record attributes that contain y-values.
		  ykeys: ['value'],
		  // Labels for the ykeys -- will be displayed when you hover over the
		  // chart.
		  labels: ['Total Orders']
		});
	</script>

<% end %>

app/views/home/home.html.erb
<section id="parallax">
		<% if logged_in? && ( current_user.role?(:customer) ) %>
			<h2 class="p-5">Hello <%= current_user.customer.first_name %>, welcome to the <em style="color: #ffc107;">Baking Factory</em><br></h2>
		<% elsif logged_in? %>
			<h2 class="p-5">Hello <%= current_user.username %>, welcome to the <em style="color: #ffc107;">Baking Factory</em><br></h2>
		<% else %>
			<h2 class="p-5">Welcome to the <em style="color: #ffc107;">Baking Factory</em><br></h2>
		<% end %>
		<p>When Alex and Mark founded the Baking Factory in 2019, they did it with the<br>goal of bringing you the freshest possible bread.<br><br>
		The Baking Factory guarantees that each of our baked goods will be<br>made fresh at our mother location in Pittsburgh, PA.<br><br>
		<a href="items">Check out some of our goods here. </a></p>
</section>



<div style="width: 40%; margin-left: 40%; margin-top: 0; padding-top: 10px; margin-bottom: 400px;">
	<h3>A word on <span style="color: #A9A9A9;">design</span>.</h3><br>
	This application uses a color hierarchy.<br><br>
	High level actions and active queries are styled with <em style="color: #ffc107;">#FFC107</em>.<br>
	While form and pagination actions use <em style="color: #007bff">#007BFF</em>.<br><br><br>
	<h4>Log Ins:</h4>
	Admin: 'mark' <span style="color: #A9A9A9;">--> Use for item management and descriptive statistics</span><br>
	Shipper: 'shipper' <span style="color: #A9A9A9;">--> for a list of items to bake</span><br>
	Baker: 'baker' <span style="color: #A9A9A9;">--> for a list of items to ship</span><br>
	User: 'user12' <span style="color: #A9A9A9;">--> to create an order in the system</span><br><br>
	The password to each of the above usernames is <strong>'secret'</strong><br><br>
	<h4>Fake Credit Card Numbers:<span style="color: #A9A9A9; font-size: .65em; font-style: normal;"> --> to purchase items</span></h4>
	Number: '4123456789012'<br>
	Expiration Month: '12'<br>
	Expiration Year: '2019'<br>

	<div style="margin-top: 50px;">
		<p style="font-size: 2em; font-weight: bold; color: #FFC107">#mk</p>
	</div>
</div>

app/views/home/item_dash.html.erb
<% if logged_in? && current_user.role?(:admin) %>
	
	<div class="row">
		<div class="col" style="margin: 5%; margin-top: 1%;">
			
			<h1><span style="color: #ffc107">Baking Factory</span> Command Center:</h1><br><br>

			<ul class="nav nav-tabs">
			  <li class="nav-item">
			    <%= link_to 'Sales Insights', sales_dash_path, class: "nav-link" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Customer Insights', customer_dash_path, class: "nav-link" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Item Insights', item_dash_path, class: "nav-link active" %>
			  </li>
			</ul>

			<div style="border: 1px solid #e5e4e2; border-top: none; display: inline;">
				<p style="width: 40%; margin: 5%; margin-top: 0px;">
				Total Items in System: <strong><%= @item_count %></strong><br>
				Total Active Items: <strong><%= @active_item_count %></strong><br><br>
				<span style="color: #a3a3a3;">View the most popular items below.</span>
				</p>

				<hr>
				<h5 style="margin-left: 45%; text-decoration: underline;">BF's Most Ordered Items:</h5>
				<%= content_tag :div, "", id: "morris_chart", data: {items: @items } %>

			</div>


		</div>
	</div>

	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

	<script type="text/javascript">
		new Morris.Bar({
		  element: 'morris_chart',
		  data: $('#morris_chart').data('items'),
		  xkey: 'label',
		  ykeys: ['value'],
		  labels: ['Total Orders']
		});
	</script>

<% end %>

app/views/home/privacy.html.erb
<div class="row">
	<div class="col" style="margin: 5%;">
		<fieldset class="border mx-4 pl-3 mb-3">
        	<legend  class="w-auto">A &amp; M Bread Express Privacy Policy</legend><br>
			<p>Any information disseminated by, provided to, or nested within the source code of this application is completely fictitious, and subject to our review.<br>Deploy this webappp at your own risk!
				<br><br>
				It really be that simple.
			</p>
	</div>
</div>

app/views/home/sales_dash.html.erb
<% if logged_in? && current_user.role?(:admin) %>
	
	<div class="row">
		<div class="col" style="margin: 5%; margin-top: 1%;">
			
			<h1><span style="color: #ffc107">Baking Factory</span> Command Center:</h1><br><br>

			<ul class="nav nav-tabs">
			  <li class="nav-item">
			    <%= link_to 'Sales Insights', sales_dash_path, class: "nav-link active" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Customer Insights', customer_dash_path, class: "nav-link" %>
			  </li>
			  <li class="nav-item">
			    <%= link_to 'Item Insights', item_dash_path, class: "nav-link" %>
			  </li>
			</ul>

			<div style="border: 1px solid #e5e4e2; border-top: none; display: inline;"><br>
				<p style="width: 40%; margin: 5%; margin-top: 0px;">
				Total Nominal Sales: <strong><%= number_to_currency @total_sales %></strong><br>
				Total Items Sold: <strong><%= @goods_count %></strong><br><br>
				<span style="color: #a3a3a3;">To view all daily sales data, refer to the chart below.</span>
				</p>
				<div class="sales-toggle">
					<%= button_to '1 month', {:controller => "home", :action => "sales_dash", :weeks => 4}, :method=>:post, params: {weeks: 4}, class: 'btn btn-primary' %>
					<%= button_to '3 months', {:controller => "home", :action => "sales_dash", :weeks => 13}, :method=>:post, params: {weeks: 13}, class: 'btn btn-primary' %>
					<%= button_to '6 months', {:controller => "home", :action => "sales_dash", :weeks => 26}, :method=>:post, params: {weeks: 26}, class: 'btn btn-primary' %>
					<%= button_to 'All Data', {:controller => "home", :action => "sales_dash", :weeks => 52}, :method=>:post, params: {weeks: 52}, class: 'btn btn-primary' %>
				</div>

				<hr>

				<div style="margin-top: 5%;">
				<h5 style="margin-left: 45%; text-decoration: underline;">Daily Sales Volume:</h5>

				<%= content_tag :div, "", id: "morris_chart", data: {sales: @orders } %>
				</div>
			</div>


		</div>
	</div>

	<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

	<script type="text/javascript">
		new Morris.Line({
		  // ID of the element in which to draw the chart.
		  element: 'morris_chart',
		  // Chart data records -- each entry in this array corresponds to a point on
		  // the chart.
		  data: $('#morris_chart').data('sales'),
		  // The name of the data record attribute that contains x-values.
		  xkey: 'date',
		  // A list of names of data record attributes that contain y-values.
		  ykeys: ['sales'],
		  // Labels for the ykeys -- will be displayed when you hover over the
		  // chart.
		  labels: ['Daily Sales']
		});
	</script>

<% end %>