config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  # Authentication routes
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end
  get "sessions/create" 
  get "sessions/destroy"

  # Special route for cart functions 
  get "/cart", to: "cart_items#show", as: "cart"
  post "/add_item", to: "cart_items#add_item", as: "add_item"
  post "/remove_item", to: "cart_items#remove_item", as: "remove_item"
  post "/clear", to: "cart_items#clear", as: "clear"
  post "/place_order", to: "cart_items#place_order", as: "place_order"
  post "/orders/new", to: 'orders#new', as: "place_new_order"

  # Shipping list
  get "/shipping", to: "orders#shipping", as: "shipping"
  post "/add_shipping", to: "orders#add_shipping", as: "add_shipping"
  post "/remove_shipping", to: "orders#remove_shipping", as: "remove_shipping"
  post "/ship_items", to: "orders#ship_items", as: "ship_items"

  # Baking List
  get "/baking", to: "orders#baking", as: "baking"

  # Item toggle
  post "/toggle", to: "items#toggle", as: "toggle"

  # Admin Dash
  get "/sales_dash", to: "home#sales_dash", as: "sales_dash"
  post "/sales_dash", to: "home#sales_dash", as: "post_sales_dash"
  get "/customer_dash", to: "home#customer_dash", as: "customer_dash"
  get "/item_dash", to: "home#item_dash", as: "item_dash"

  # get 'customers/new', to: 'customers#new', as: :signup
  # get 'users/new', to: 'users#new', as: :signup
  # get 'user/edit', to: 'users#edit', as: :edit_current_user
  
  # get 'sessions', to: 'sessions#new', as: :login
  get 'sessions', to: 'sessions#destroy', as: 'logout_user'
  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # get modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # Relationships
  has_many :orders
  has_many :addresses
  belongs_to :user

  # Allow user to be nested within customer
  accepts_nested_attributes_for :user, reject_if: ->(user) { user[:username].blank? }, allow_destroy: true
  attr_accessor :username, :password, :password_confirmation

  # Searchability 
  def self.search_by(term)
    where(["LOWER(first_name) LIKE :term OR  LOWER(last_name) LIKE :term OR  LOWER(email) LIKE :term", { term: "%#{term.downcase}%", term: "%#{term.downcase}%", term: "%#{term.downcase}%" }])
  end

  # Scopes
  scope :alphabetical,  -> { order(:last_name).order(:first_name) }

  # Validations
  validates_presence_of :last_name, :first_name
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"


  # Callbacks
  before_save :reformat_phone
  before_update :deactive_user_if_customer_inactive
  before_destroy :cannot_destroy_object

  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end

  def proper_name
    "#{first_name} #{last_name}"
  end

  def billing_address
    self.addresses.active.billing.first
  end

  # Private methods
  private
  def reformat_phone
    self.phone = self.phone.to_s.gsub(/[^0-9]/,"")
  end

  def deactive_user_if_customer_inactive
    if !self.active && !self.user.nil?
      self.user.active = false
      self.user.save
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_customer, only: [:show, :edit, :update, :toggle_activity]
  before_action :check_login, except: [:new, :create]
  authorize_resource except: [:new, :create] 
  
  def index
    if params[:search].present? && !(["inactive","active"].include?(params[:search]))
      @customers = Customer.all.alphabetical.search_by(params[:search]).paginate(:page => params[:page]).per_page(10)      
    # Categories
    elsif params[:search] == "active"
      @customers = Customer.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    elsif params[:search] == "inactive"
      @customers = Customer.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
    else 
      @customers = Customer.all.alphabetical.paginate(:page => params[:page]).per_page(10)      
    end
  end

  def show
    @previous_orders = @customer.orders.chronological
    @addresses = @customer.addresses
    customer_orders = @previous_orders.map{|o| o.id}
    @previous_items = OrderItem.where(order_id: customer_orders).take(5)
  end

  def new
    @customer = Customer.new
    @user = @customer.build_user
  end

  def edit
    # reformat phone w/ dashes when displayed for editing (preference; not required)
    @customer.phone = number_to_phone(@customer.phone)
    user = (@customer.user.nil? ? @customer.build_user : @customer.user)
  end

  def create
    @customer = Customer.new(customer_params)
    @user = User.new(customer_params.to_h.slice(:username, :password, :password_confirmation))
    @user.role = "customer"

    if !@user.save
      @customer.valid? 
      render action: 'new'
    else 
      @customer.user_id = @user.id
      if @customer.save 
        flash[:notice] = "Created a new customer: #{@customer.proper_name}."
        if logged_in? && ( current_user.role?(:admin) )
          redirect_to customer_path(@customer)
        else 
          redirect_to login_path
        end
        # The usual: redirect_to login_path
      else
        flash[:notice] = "Customer could not be saved."
        render "customers/new"
      end
    end 
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: "#{@customer.proper_name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def toggle_activity
    @customer.toggle!(:active)
  end

  private
  def convert_user_role
    unless current_user.nil? || current_user.role?(:admin)
      # if you aren't admin, we are overriding the role param to be customer
      params[:customer][:user_attributes][:role] = "customer"
    end
  end

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    convert_user_role
    params.require(:customer).permit(:first_name, :last_name, :email, :phone, :active, :username, :password, :password_confirmation)  
  end

end

app/views/customers/_active_customers.html.erb
<% if @active_customers.empty? %>
  <h4>No active customers at this time.</h4>
<% else %>
  <h4>Active Customers</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="225">Name</th>
        <th width="125">Phone</th>
        <th width="200">Email</th>
      </tr>
    </thead>
    <tbody>
      <% @active_customers.each do |customer| %>
        <tr>
          <td><%= link_to customer.name, customer_path(customer) %></td>
          <td><%= number_to_phone customer.phone %></td>
          <td><%= mail_to customer.email, customer.email, encode: "javascript"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate @active_customers, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  
<% end %>
<p>&nbsp;</p>

app/views/customers/_customer_details.html.erb
<h3><%= @customer.proper_name %></h3>

<p>
  <b>Phone</b>: <%= number_to_phone @customer.phone %>
</p>

<p>
  <b>Email</b>: <%= mail_to @customer.email, @customer.email, encode: "javascript" %>
</p>

<p>
  <b>Active</b>: <%= @customer.active ? 'Yes' : 'No' %>
</p>

<p>
  <em>A Baking Factory customer since <%# @customer.created_at.year %>.</em>
</p>

app/views/customers/_fields.html.erb
    <!-- Show User Errors First -->
    <% if action_name == "new" && @user.errors.any? %>
        <% @user.errors.full_messages.uniq.each do |message| %>
          <div class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
              <%= message %>
          </div>
        <% end %>
    <% end %>  

    <%= f.label :first_name %> 
    <%= f.text_field :first_name, class: "form-control" %><br>
    <%= f.label :last_name %> 
    <%= f.text_field :last_name, class: "form-control" %><br>
    <%= f.label :phone %> 
    <%= f.text_field :phone, class: "form-control" %><br>
    <%= f.label :email %> 
    <%= f.text_field :email, class: "form-control" %><br>
    
    <% if logged_in? && current_user.role?(:admin) || !logged_in? %>
    <hr>
    <!-- Also Render Nested User Fields -->
    <div class="form-group">
      <%= f.label :username %> 
      <%= f.text_field :username, class: "form-control" %><br>
      <%= f.label :password %> 
      <%= f.password_field :password, class: "form-control" %><br>
      <%= f.label "Confirm Password" %> 
      <%= f.password_field :password_confirmation, class: "form-control" %><br>
      <% if logged_in? && current_user.role?(:admin) %>
      <%= f.check_box :active, class: "form-control", style: "width: 2%; height: 16px; display: inline;" %> Make User Active<br>
      <% end %> 
    </div>
    <% end %>

    <% if logged_in? && current_user.role?(:admin) %>
    <%= f.check_box :active, class: "form-control", style: "width: 2%; height: 16px; display: inline;" %> Make Customer Active
    <% end %>

app/views/customers/_form.html.erb
<%= simple_form_for @customer, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Customer</legend>

    <%= f.input :first_name, input_html: {class: "avg"} %>
    <%= f.input :last_name, input_html: {class: "avg"} %>
    <%= f.input :phone, input_html: {class: "avg"} %>
    <%= f.input :email, input_html: {class: "avg"} %>
    <%= f.input :active %>
    


    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', customers_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/customers/_inactive_customers.html.erb
<% unless @inactive_customers.empty? %>
  <div class="panel clearfix">
    <h3>Inactive Customers</h3>
    <ul>
      <% @inactive_customers.each do |customer| %>
        <li><%= link_to customer.name, customer_path(customer) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/_user_fields.html.erb
<%= f.label :username %> 
<%= f.text_field :username, class: "form-control" %><br>
<%= f.label :password %> 
<%= f.text_field :password, class: "form-control" %><br>
<%= f.label :password_confirmation %> 
<%= f.text_field :password_confirmation, class: "form-control" %><br>
<% if logged_in? && current_user.role?(:admin) %>
<%= f.check_box :active, class: "form-control", style: "width: 2%; height: 16px; display: inline;" %> Make User Active<br>
<% end %> 

app/views/customers/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @customer, 
                                                        type_of_form: "Edit Customer",
                                                        fields: "fields"} %>

app/views/customers/index.html.erb
<div class="row" style="margin: 5%; margin-top: 10%;">
	
	<div class="col">
		<h4>Customer Management:</h4>
		<p style="color: #999;">Search by name with the toolbar on your right.</p>
	</div>

	<div class="col" style="width: 40%; float: right; position: absolute; right: 5%;">
	<%= form_for "", :class => "form-inline", url: customers_path, role: 'search', method: :get do %>
		<span>
		<%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
		</span>
		<span style="float: right; margin-top: 1%;">
		<%= submit_tag "Search",:class => "btn btn-warning", name: nil%>
		</span> 
		<a href="customers"><button type="button" class="btn btn-outline-warning" style="float: right; margin-top: 1%; margin-right: 1%;">Show Me Everyone</button></a>
		<a href="/customers?utf8=✓&search=active"><button type="button" class="btn btn-outline-warning" style="float: right; margin-top: 1%; margin-right: 1%;">Active</button></a>
		<a href="/customers?utf8=✓&search=inactive"><button type="button" class="btn btn-outline-warning" style="float: right; margin-top: 1%; margin-right: 1%;">Inactive</button></a>
	<% end %>
	</div>
</div>


<div class="row", style="width: 90%; margin: 5%; margin-top: 10%; margin-top: 0%; border-top: 1px solid #a3a3a3; padding-top: 2%;">

	<% if @customers.nil? || @customers.empty? %>
	  <p style="padding-top: 20px">No customers in the system!</p>
	<% else %>
	  <div>
	  <%= will_paginate @customers, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
	  </div>
	  <div style="display: inline; margin-left: .5%; margin-bottom: 5px;">
	    <%= link_to "Add a New Customer", new_customer_path, class: 'btn btn-primary' %> 
	  </div>
	  
	  <table class="table table-striped" style="width: 100%; border: 1px;">
	    <thead>
	      <tr>
	        <th width="50">Name</th>
	        <th width="50">Email</th>        
	        <th width="50">Phone</th>            
	        <th width="50">Active</th>   
	        <th width="50">Edit</th>        
	      </tr>
	    </thead>
	    <tbody>
	      <% @customers.each do |customer| %>
	        <tr>
	          <td><%= link_to customer.name, customer_path(customer) %></td>
	          <td><%= mail_to(customer.email) %></td>
	          <td><%= customer.phone.insert(3, '-').insert(-5, '-') %></td>
	          <td>&nbsp;&nbsp;&nbsp;&nbsp;
	          	<% if customer.active %>
	          		<i class='material-icons'>done</i>
	          	<% else %>
	          	<% end %> 	
	           </td>
	          <td>
	            <%= link_to edit_customer_path(customer) do %>
	              <i class="material-icons">edit</i>
	            <% end %>
	          </td>
	        </tr>
	      <% end %>
	    </tbody>
	  </table>
	    
	  <%= will_paginate @customers, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
	  
	<% end %>

</div> 

	

app/views/customers/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @customer, 
                                                        type_of_form: "New Customer",
                                                        fields: "fields"} %>

app/views/customers/show.html.erb
<div class="row">
  <div class="col" style="margin: 5%;">
   
    <div class="card mb-3">
	  <div class="row no-gutters">
		<div class="col-md-6">
	  	<div class="card-body">
	    	<h5 class="card-title">Customer Details</h5>
	    	<p style="color: #a3a3a3;">View your addresses, orders, and recently ordered items below.</p>
	        <strong>Name:</strong>
	        <% if @customer.created_at.nil? %>
	        <p><%= @customer.name %></p>
	        <% else %>
	        <p><%= @customer.name %><small class="text-muted">. A Baking Factory customer since <%= @customer.created_at.strftime('%m/%d/%Y') %></small></p>
	        <% end %>
	    	<strong>Email:</strong>
	        <p><%= @customer.email %></p>
	        <strong>Phone:</strong>
	        <p><%= @customer.phone.insert(3, '-').insert(-5, '-') %></p>
	        <strong>Username:</strong>
	        <p><%= @customer.user.username %></p>
	        <strong>Active:</strong>
	        <% if @customer.active %> 
	        	<p><i class='material-icons'>done</i></p>
	        <% else %>
	        	<p><i class='material-icons'>clear</i></p>
	        <% end %>
	        <% if logged_in? && current_user.role?(:admin) %>
	        <%= link_to 'All Customers', customers_path, class: "btn btn-outline-primary" %> 
	        <% end %>
	        <%= link_to 'Edit Customer', edit_customer_path(@customer), class: "btn btn-outline-primary" %> 
	  	</div>
	  	</div>

	  </div>
	</div>

  </div>
</div>

<div class="row" style="margin-top: -5%; margin-left: 3%;">
  	<% @previous_items.each do |oi| %>
  	<div class="col" style="">
        <div class="card" style="width: 78%;">
          <% if oi.item.category == 'bread' %>
          <%= image_tag("bread.jpg", class: 'card-img-top')%>
          <% elsif oi.item.category == 'muffins' %>
          <%= image_tag("muffins.jpg", class: 'card-img-top img-fluid' )%>
          <% else %>
          <%= image_tag("pastries.jpg", class: 'card-img-top img-fluid')%>
          <% end %>
          <div class="card-body">
            <strong class="card-title"><%= oi.item.name %></strong>
            <p class="card-text">
            	<%= number_to_currency oi.item.current_price %> | <%= oi.item.units_per_item %> <%= oi.item.category == 'bread' ? 'loaf' : oi.item.category %><br>
            </p>
          	<% if logged_in? && (current_user.role?(:admin) || current_user.role?(:customer)) %>
            <%= button_to 'Add to Cart', {:controller => "cart_items", :action => "add_item", :item_id => oi.item.id}, :method=>:post, params: {item_id: oi.item.id}, class: "btn btn-primary", style: "margin-top: 5px;"  %>
          	<% else %>
          	<% end %> 
          </div>
        </div>
    </div>
    <% end %> 
  </div>
</div>


<div class="row">
  <div class="col" style="margin: 5%; margin-top: 1%;">
   
    <div class="card mb-3">
	  <div class="row no-gutters">
		<div class="col-md-8">
	  	<div class="card-body">
	    	<h5 class="card-title">Addresses</h5>
	        <table class="table" style="width: 152.5%; border: 1px;">
				    <thead>
				      <tr>
				        <th width="50">Recipient</th>            
				        <th width="50">Address</th> 
				        <th width="50">Billing</th>         
				        <th width="50">Active</th>  
				        <th width="50">Edit</th> 
				        <% if logged_in? && current_user.role?(:admin) %>
				        	<th width="50">Delete</th> 
				        <% else %>
				        <% end %>
				      </tr>
				    </thead>
				    <tbody>
				      <% @addresses.each do |address| %>
				        <tr>
				          <td><%= address.recipient %></td>
				          <td><%= address.street_1 %> <%= address.street_2.nil? ? "" : address.street_2 %> <%= address.city %>, <%= address.state %> <%= address.zip %></td>
				          <td>&nbsp;&nbsp;&nbsp;&nbsp;
				          	<% if address.is_billing %>
				          		<i class='material-icons'>done</i>
				          	<% else %>
				          	<% end %> 	
				          </td>
				          <td>&nbsp;&nbsp;&nbsp;&nbsp;
				          	<% if address.active %>
				          		<i class='material-icons'>done</i>
				          	<% else %>
				          	<% end %>
				          </td>
				          <td>&nbsp;
				            <%= link_to edit_address_path(address) do %>
				              <i class="material-icons">edit</i>
				            <% end %>
				          </td>
				          <% if logged_in? && current_user.role?(:admin) %>
					          <td>&nbsp;&nbsp;
					            <%= link_to(address_path(address), method: :delete, data: { confirm: 'Are you sure?' }) do %>
					              <i class="material-icons">delete</i>
					            <% end %>
					          </td>
					        <% else %>
				        	<% end %>
				        </tr>
				      <% end %>
				    </tbody>
				  </table>
				  <%= link_to 'Add an Address', new_address_path, class: "btn btn-outline-primary" %> 
	  	</div>
	  	</div>
	  </div>
	</div>

  </div>
</div>

<div class="row">
<div class="col" style="margin: 5%; margin-top: -5%;">
	<div class="card mb-3">
	  <div class="card-body">
	    <h5 class="card-title">Order History</h5>
	    <p class="card-text">
	    	<table class="table" style="width: 100%; border: 1px;">
			    <thead>
			      <tr>
			        <th width="50">Date</th>
			        <th width="50">Recipient</th>        
			        <th width="50">Cost</th>            
			        <th width="50">Items</th>
			      </tr>
			    </thead>
			    <tbody>
			      <% @previous_orders.each do |order| %>
			        <tr>
			          <td><%= link_to order.date, order_path(order) %></td>
			          <td><%= order.address.recipient %></td>
			          <td><%= number_to_currency order.grand_total %></td>
			          <td>
			          	<% order.order_items.order(:id).each do |item| %> 
			          	  <% if item == order.order_items.order(:id).last %>
			          	  	<span><%= link_to item.item.name, item_path(item.item) %>. </span>
			          	  <% else %>
			          		<span><%= link_to item.item.name, item_path(item.item) %>, </span>
			          	  <% end %>
			          	<% end %> 
			          </td>
			        </tr>
			      <% end %>
			    </tbody>
			</table>
	    </p>
	    <% if logged_in? && current_user.role?(:admin) %>
	    <%= link_to 'All Orders', orders_path, class: "btn btn-outline-primary", style: "margin-bottom: 1%;" %>
	    <% end %>
	  </div>
	</div>
</div>
</div>

<!-- Carousel Styles & Scripts -->
<!-- Credit to: https://codepen.io/kreigd/pen/ybYNoN -->

<style type="text/css">
  @media (min-width: 768px) {
  /* show 3 items */
  .carousel-inner .active,
  .carousel-inner .active + .carousel-item,
  .carousel-inner .active + .carousel-item + .carousel-item {
    display: block;
  }

  .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left),
  .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left) + .carousel-item,
  .carousel-inner .carousel-item.active:not(.carousel-item-right):not(.carousel-item-left) + .carousel-item + .carousel-item {
    transition: none;
  }

  .carousel-inner .carousel-item-next,
  .carousel-inner .carousel-item-prev {
    position: relative;
    transform: translate3d(0, 0, 0);
  }

  .carousel-inner .active.carousel-item + .carousel-item + .carousel-item + .carousel-item {
    position: absolute;
    top: 0;
    right: -33.3333%;
    z-index: -1;
    display: block;
    visibility: visible;
  }

  /* left or forward direction */
  .active.carousel-item-left + .carousel-item-next.carousel-item-left,
  .carousel-item-next.carousel-item-left + .carousel-item,
  .carousel-item-next.carousel-item-left + .carousel-item + .carousel-item,
  .carousel-item-next.carousel-item-left + .carousel-item + .carousel-item + .carousel-item {
    position: relative;
    transform: translate3d(-100%, 0, 0);
    visibility: visible;
  }

  /* farthest right hidden item must be abso position for animations */
  .carousel-inner .carousel-item-prev.carousel-item-right {
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
    display: block;
    visibility: visible;
  }

  /* right or prev direction */
  .active.carousel-item-right + .carousel-item-prev.carousel-item-right,
  .carousel-item-prev.carousel-item-right + .carousel-item,
  .carousel-item-prev.carousel-item-right + .carousel-item + .carousel-item,
  .carousel-item-prev.carousel-item-right + .carousel-item + .carousel-item + .carousel-item {
    position: relative;
    transform: translate3d(100%, 0, 0);
    visibility: visible;
    display: block;
    visibility: visible;
  }
}
</style>

<script type="text/javascript">
	$(document).ready(function() {
	  $("#myCarousel").on("slide.bs.carousel", function(e) {
	    var $e = $(e.relatedTarget);
	    var idx = $e.index();
	    var itemsPerSlide = 3;
	    var totalItems = $(".carousel-item").length;

	    if (idx >= totalItems - (itemsPerSlide - 1)) {
	      var it = itemsPerSlide - (totalItems - idx);
	      for (var i = 0; i < it; i++) {
	        // append slides to end
	        if (e.direction == "left") {
	          $(".carousel-item")
	            .eq(i)
	            .appendTo(".carousel-inner");
	        } else {
	          $(".carousel-item")
	            .eq(0)
	            .appendTo($(this).find(".carousel-inner"));
	        }
	      }
	    }
	  });
	});
</script>